version: '3.0'

services:
  dev:
    container_name: crawlers_dev
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: bash -c "npm run migrate:latest && npm run start:dev"
    depends_on:
      - postgres
    restart: always
  prod:
    container_name: crawlers_prod
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: bash -c "npm run migrate:latest && npm run start:prod"
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: